hyperParams <- c(configuration$MPR_MIN,configuration$MPR_MAX,configuration$DNR_MIN,configuration$DNR_MAX,configuration$FCH_MIN,configuration$FCH_MAX,as.numeric(configuration$HCO_MIN),as.numeric(configuration$HCO_MAX),configuration$possible_interactions, configuration$THRESHOLD_MODELS,configuration$standard_deviation_factor)
names(hyperParams) <- c("MPR_MIN", "MPR_MAX", "DNR_MIN", "DNR_MAX", 'FCH_MIN', "FCH_MAX", 'HCO_MIN', "HCO_MAX", "possible_interactions", "THRESHOLD_MODELS", "standard_deviation_factor")
stochParams <- c(configuration$NOISE_LEVELS,configuration$NOISE_SCALING_FACTOR, configuration$MAX_NOISE,as.numeric(configuration$GENE_NOISE_SCALING),as.numeric(configuration$SHOT_NOISE_SCALING))
names(stochParams) <- c("NOISE_LEVELS", "NOISE_SCALING_FACTOR", "MAX_NOISE", "GENE_NOISE_SCALING", "SHOT_NOISE")
simParams <- c(configuration$NUM_MODELS, configuration$PARAMETER_RANGE, configuration$STEP_SIZE, configuration$SIM_TIME, configuration$INITIAL_CONDITIONS, configuration$OUTPUT_PRECISION)
names(simParams) <- c("NUM_MODELS", "PARAMETER_RANGE", "STEP_SIZE", "SIM_TIME","INITIAL_CONDITIONS","OUTPUT_PRECISION")
simulationData <- list(simParams,stochParams,hyperParams)
names(simulationData) <- c("simParams", "stochParams","hyperParams")
saveRDS(simulationData, "data/simulationData.RDS")
