# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generateThresholds <- function(gene_interaction, threshold_gene, simulationData) {
    invisible(.Call('_GeneVyuha_generateThresholds', PACKAGE = 'GeneVyuha', gene_interaction, threshold_gene, simulationData))
}

simulate_GRN <- function(gene_interaction, threshold_gene, g_min, g_max, k_min, k_max, possible_interactions, model_count_max, threshold_max, h, lambda_min, lambda_max, n_min, n_max, tot_time, standard_deviation_factor, number_gene, D_max, D_shot_scaling, GENE_NOISE_SCALING, D_levels, D_scaling, output_precision, ANNEALING, INITIAL_CONDITIONS, filename, parameters_file, readIC, timeSeries) {
    .Call('_GeneVyuha_simulate_GRN', PACKAGE = 'GeneVyuha', gene_interaction, threshold_gene, g_min, g_max, k_min, k_max, possible_interactions, model_count_max, threshold_max, h, lambda_min, lambda_max, n_min, n_max, tot_time, standard_deviation_factor, number_gene, D_max, D_shot_scaling, GENE_NOISE_SCALING, D_levels, D_scaling, output_precision, ANNEALING, INITIAL_CONDITIONS, filename, parameters_file, readIC, timeSeries)
}

selectIc <- function(gene_interaction, nIc, model_count_max, outputPrecision, fileName) {
    invisible(.Call('_GeneVyuha_selectIc', PACKAGE = 'GeneVyuha', gene_interaction, nIc, model_count_max, outputPrecision, fileName))
}

simulateNetwork <- function(gene_interaction, simulationData, tmpFileName, genThresh = TRUE, genModelParams = TRUE, genIc = TRUE, integrate = TRUE, timeSeries = FALSE, annealing = FALSE) {
    invisible(.Call('_GeneVyuha_simulateNetwork', PACKAGE = 'GeneVyuha', gene_interaction, simulationData, tmpFileName, genThresh, genModelParams, genIc, integrate, timeSeries, annealing))
}

